name: sasmobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  async: ^2.11.0
  auto_size_text: ^3.0.0
  decimal: ^2.3.3
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_exit_app: ^1.1.2
  flutter_fadein: ^2.0.0
  flutter_keychain: ^2.4.0
  flutter_vibrate: ^1.3.0
  get: ^4.6.6
  flutter_native_splash: ^2.4.0
  get_storage: ^2.1.1
  keyboard_dismisser: ^3.0.0
  loader: ^1.0.0
  local_auth: ^2.2.0
  qr_bar_code_scanner_dialog: ^0.0.5
  qr_flutter: ^4.1.0
  result_type: ^0.2.0
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: resources/sasPay_white.png
  image_dark:  resources/sasPay_dark.png
  color_dark: "#2f547d"
  android_12:
    color: "#ffffff"
    image_dark:  resources/sasPay_dark.png
    image: resources/sasPay_white.png
    color_dark: "#2f547d"
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/Icon.png"
  min_sdk_android: 20
  remove_alpha_ios: true
  image_path_ios: "resources/icon_ios.png"
  adaptive_icon_background: "#ffffff"